# Файл docker-compose должен начинаться с тега версии
# Мы используем "4.41.2"

# docker-composes работает с сервисами
# 1 сервис = 1 контейнер
# Сервисом может быть клиент, сервер, сервер баз данных и т.д.
# Раздел, в котором будут описаны сервисы, начинается с 'services'

services:                 # Секция определения всех сервисов (контейнеров)
                
                          # Нам нужно два сервиса
                          # Первый сервис (контейнер): сервер
                          # Назвать его можно так, как нужно разработчику
                          # Понятное название сервиса помогает определить его роль
  web:                    # Сервис №1: Веб-сервер
    build: .              # Собирает образ из Dockerfile в текущей директории
    ports:                # Пробрасывает порт 80 контейнера на 8080 хоста
      - "8080:80"
    depends_on:           # Ждёт запуска сервиса db перед стартом
      - db                
    volumes:
      - ./:/var/www/html  # Монтирует текущую папку в контейнер

  db: # Сервис №2: База данных MySQL
    