# UwU
# docker-composes работает с сервисами
# 1 сервис = 1 контейнер
# Сервисом может быть клиент, сервер, сервер баз данных и т.д.
# Раздел, в котором будут описаны сервисы, начинается с 'services'
services:                 # Секция определения всех сервисов (контейнеров)             
                          # Нам нужно два сервиса
                          # Первый сервис (контейнер): сервер
                          # Назвать его можно так, как нужно разработчику
                          # Понятное название сервиса помогает определить его роль
  web:
    container_name: web   # Сервис №1: Веб-сервер
    build: .              # Собирает образ из Dockerfile в текущей директории
    ports:                # Пробрасывает порт 80 контейнера на 8080 хоста
      - "8080:80"
    depends_on:           # Ждёт запуска сервиса db перед стартом
      - db                
    volumes:
      - ./:/var/www/html  # Монтирует текущую папку в контейнер

  db:                 # Сервис №2: База данных
    image: postgres:17  # Версия
    container_name: db # Имя контейнера
    environment:
      POSTGRES_DB: vuln_db  # Правильная переменная для Postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"  # Стандартный порт Postgres
volumes:
  postgres_data:  # Объявляем том
#docker-compose down -v  |Удаляет все данные
#docker-compose up -d    |Запускает заново